# Generated by Django 2.1.4 on 2020-02-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Articale_url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_text', models.CharField(max_length=100)),
                ('webpage_url', models.URLField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='articale',
            name='Webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Webpage'),
        ),
        migrations.AddField(
            model_name='articale',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tag'),
        ),
    ]
