# Generated by Django 2.1.4 on 2020-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_webpage_web_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='web_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
