# Generated by Django 2.1.4 on 2020-02-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_webpage_web_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('title_url', models.URLField(max_length=100)),
                ('Webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Webpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='articale',
            name='Webpage',
        ),
        migrations.RemoveField(
            model_name='articale',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Articale',
        ),
    ]
