# Generated by Django 2.1.4 on 2020-02-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200211_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.CharField(max_length=100)),
                ('article_url', models.URLField(max_length=100)),
                ('Webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Webpage')),
                ('tag', models.ManyToManyField(to='myapp.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='title',
            name='Webpage',
        ),
        migrations.RemoveField(
            model_name='title',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
